# ✈️ Singapore Airlines Customer Satisfaction Analysis

## 📌 Project Overview

### This project focuses on analyzing customer satisfaction data for Singapore Airlines using a large-scale passenger dataset stored in Azure SQL Database and accessed through Jupyter Notebook with Python. The dataset represents over 100,000 passenger reservations, including booking behavior, cabin class, fare paid, luggage details, service preferences, and customer feedback ratings.

### The primary goal of this analysis is to understand how different service, pricing, and travel factors influence passenger experience and loyalty. By applying exploratory data analysis (EDA), visualization, and statistical techniques, this project aims to uncover patterns that help explain what drives customer satisfaction in a premium airline environment.

## --------------------------------------------------------------

## 🎯 Objectives

### The objectives of this project are to:

Analyze overall passenger satisfaction levels.

Identify the impact of cabin class, fare, and booking channel on ratings.

Explore customer preferences such as seat choice, meal options, and entertainment needs.

Understand upgrade behavior and its relationship with experience.

Examine loyalty indicators such as recommendation intent and first-time flyers.

Provide actionable insights that airlines can use to improve service quality and revenue strategies.

In [5]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import pyodbc
print(pyodbc.drivers())
import urllib

['SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)', 'ODBC Driver 18 for SQL Server']

In [11]:
server = "sql-db-powerbi.database.windows.net"
username = "sqlpowerbi@sql-db-powerbi"
database = "free-sql-db-8691499"
password = "Brisaus2026@"
driver = "ODBC Driver 18 for SQL Server"

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"UID={username};"
    f"PWD={password};"
    "Encrypt=yes;"
    "TrustServerCertificate=no;"
    "Connection Timeout=30;"
)


engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")
df = pd.read_sql("SELECT * FROM singapore_satisfaction_main", engine)
df.head()

,ReservationNumber,FlightNumber,CabinClass,FlightFareAUD,BookingOption,Origin,Destination,PaidForSeat,LuggageWeightKG,CabinBag,WantedUpgrade,SeatPreference,EntertainmentScreenRequired,Transiting,Rating,MealOption,RecommendOthers,FirstTimeFlyingSQ
0,UTKXCJHP,SQ317,Economy,999.34,Agent,Singapore,Tokyo,False,21.200001,None,False,Window,False,True,4.6,Vegetarian Pasta,True,False
1,THO8AXMS,SQ221,Economy,1204.61,Agent,Singapore,Melbourne,False,20.600000,True,True,Window,True,True,3.9,Vegan Curry,True,False
2,VXQA18CR,SQ317,Premium Economy,1715.84,None,Singapore,Tokyo,False,26.600000,True,False,Aisle,True,False,3.8,Seafood Noodles,True,False
3,N674CRW1,SQ318,Economy,1008.51,Agent,Tokyo,Singapore,False,19.200001,True,False,Window,True,True,3.8,Vegan Curry,True,True
4,WVZ6NTWA,SQ608,Economy,948.39,Agent,Seoul,Singapore,False,10.500000,None,True,Aisle,None,True,2.9,Vegetarian Pasta,False,True

In [12]:
df.shape

(120000, 18)

In [13]:
df.isnull()

,ReservationNumber,FlightNumber,CabinClass,FlightFareAUD,BookingOption,Origin,Destination,PaidForSeat,LuggageWeightKG,CabinBag,WantedUpgrade,SeatPreference,EntertainmentScreenRequired,Transiting,Rating,MealOption,RecommendOthers,FirstTimeFlyingSQ
0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
119996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
119997,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
119998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
119999,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False

In [17]:
# df.describe(include = 'all')

In [16]:
df.describe()

       FlightFareAUD  LuggageWeightKG         Rating
count  116400.000000    116400.000000  120000.000000
mean     1556.343296        21.986393       4.067517
std      1167.931745         5.996457       0.640941
min        25.190000         5.000000       1.000000
25%       856.735000        17.900000       3.600000
50%      1077.170000        22.000000       4.100000
75%      1534.055000        26.000000       4.600000
max      5866.600000        44.900002       5.000000

In [19]:
# df.isnull().mean()

## Data Cleaning & Preparation

In [ ]:
# Lets check missing values.